# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
author: "Rutgers Christians on Campus"
title: "Rutgers Christians on Campus"
url: "ruchristiansoncampus.github.io"
