# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
author: "Rutgers Christians on Campus"
title: "Rutgers Christians on Campus"
url: "ruchristiansoncampus.github.io"
